// Automatically generated by astro-icon
// 8a269f178bc6b03374a93521d17c46890efbe43afd5982c3275e969120b96408

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "dark"
		| "light"
		| "linkedin"
		| "logo";
}